name: SonarQube PR Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonar-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important for SonarQube analysis

      - name: SonarQube Community PR Scan
        uses: ./path/to/sonar-action # Or org/repo@tag
        with:
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: "my-project-key"
          github-token: ${{ secrets.GITHUB_TOKEN }}
